services:
  zabbix-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - zabbix-db:/var/lib/mysql
    networks:
      - zabbix-net

  zabbix-server:
    hostname: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    depends_on:
      - zabbix-db
    volumes:
      - ./zabbix-alertscripts:/usr/lib/zabbix/alertscripts:rw
      - ./zabbix-externalscripts:/usr/lib/zabbix/externalscripts:rw
      # - send_telegram.sh:/usr/lib/zabbix/alertscripts/send_telegram.sh
    expose:
      - "10051"
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
      TZ: Europe/Kiev
    depends_on:
      - zabbix-db
      - zabbix-server
    volumes:
      - zabbix-web:/var/lib/zabbix
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  this-server-agent:
    image: zabbix/zabbix-agent:latest
    hostname: this-server-agent
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
    # volumes:
      # - ./zabbix_agentd.conf:/etc/zabbix/zabbix_agent.conf
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
    expose:
      - "10050"
    ports:
      - "10050:10050"

volumes:
  zabbix-db:
  zabbix-alertscripts:
  zabbix-externalscripts:
  zabbix-web:

networks:
  zabbix-net:
    driver: bridge


